name: Test Flake Environments

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-envs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Activate Nix Shell
      run: |
        nix develop

    - name: Test Flake Environments
      run: |
        ./test-flake-envs.sh

